In [12]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
try:
    from statsmodels.stats.proportion import proportion_confint
except ModuleNotFoundError:
    %pip install statsmodels
    from statsmodels.stats.proportion import proportion_confint
import numpy as np

conn = sqlite3.connect(r'C:\Users\nihad\OneDrive\Desktop\project 3.1\project 3.1\data\raw\ipl.db')


def q(sql):
    return pd.read_sql_query(sql, conn)

In [13]:
stats.binomtest(613, 1187, 0.5).pvalue

np.float64(0.2700389712415702)

In [14]:
#Does winning the toss help you win the match?

q(""" select count(*) as n,
    sum(case when toss_winner = match_winner
             then 1 else 0 end)as k
from matches_clean
where result = 'win';""")

      n    k
0  1187  613

In [16]:
P=stats.binomtest(613,1187,0.5).pvalue
ci=proportion_confint(613,1187,method='wilson')
print(P)
print(ci)

0.2700389712415702
(0.48799203833275506, 0.5447579131499739)

In [17]:
#Does the decision taken after the toss matter?
#h0- Captains who choose to bat and captains who 
# choose to field win equally often. The gap we saw is luck.
#h1-The two choices do not win equally often.

q("""SELECT toss_decision,
      SUM(CASE WHEN toss_winner = match_winner
                THEN 1 ELSE 0 END) AS WON,
      SUM(CASE WHEN toss_winner <> match_winner
                THEN 1 ELSE 0 END) AS lost
FROM matches_clean
WHERE result = 'win'
GROUP BY toss_decision;"""                                                            )

  toss_decision  WON  lost
0           bat  184   218
1         field  429   356